// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/transformOptionPricer.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// glPricer_cpp
arma::cube glPricer_cpp(const arma::cube& strikeMat, const arma::mat& mkt, const arma::vec& glWts, const arma::vec& glNodes, arma::cx_cube& cfVals, int Nfactors, double alpha, double sigmaRef);
RcppExport SEXP _transformOptionPricer_glPricer_cpp(SEXP strikeMatSEXP, SEXP mktSEXP, SEXP glWtsSEXP, SEXP glNodesSEXP, SEXP cfValsSEXP, SEXP NfactorsSEXP, SEXP alphaSEXP, SEXP sigmaRefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type strikeMat(strikeMatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mkt(mktSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type glWts(glWtsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type glNodes(glNodesSEXP);
    Rcpp::traits::input_parameter< arma::cx_cube& >::type cfVals(cfValsSEXP);
    Rcpp::traits::input_parameter< int >::type Nfactors(NfactorsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaRef(sigmaRefSEXP);
    rcpp_result_gen = Rcpp::wrap(glPricer_cpp(strikeMat, mkt, glWts, glNodes, cfVals, Nfactors, alpha, sigmaRef));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_transformOptionPricer_glPricer_cpp", (DL_FUNC) &_transformOptionPricer_glPricer_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_transformOptionPricer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
