// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// glPricer_cpp
arma::cube glPricer_cpp(const arma::cube& strikeMat, const arma::mat& mkt, const arma::vec& glWts, const arma::vec& glNodes, const arma::cx_cube& cfVals, int Nfactors, double alpha, int Npts, double sigmaRef);
RcppExport SEXP transformOptionPricer_glPricer_cpp(SEXP strikeMatSEXP, SEXP mktSEXP, SEXP glWtsSEXP, SEXP glNodesSEXP, SEXP cfValsSEXP, SEXP NfactorsSEXP, SEXP alphaSEXP, SEXP NptsSEXP, SEXP sigmaRefSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::cube& >::type strikeMat(strikeMatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mkt(mktSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type glWts(glWtsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type glNodes(glNodesSEXP);
    Rcpp::traits::input_parameter< const arma::cx_cube& >::type cfVals(cfValsSEXP);
    Rcpp::traits::input_parameter< int >::type Nfactors(NfactorsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type Npts(NptsSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaRef(sigmaRefSEXP);
    __result = Rcpp::wrap(glPricer_cpp(strikeMat, mkt, glWts, glNodes, cfVals, Nfactors, alpha, Npts, sigmaRef));
    return __result;
END_RCPP
}
