# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
glPricer_cpp <- function(strikeMat, mkt, glWts, glNodes, cfVals, Nfactors, alpha = 0, Npts = 64L, sigmaRef = 1.0) {
    .Call('transformOptionPricer_glPricer_cpp', PACKAGE = 'transformOptionPricer', strikeMat, mkt, glWts, glNodes, cfVals, Nfactors, alpha, Npts, sigmaRef)
}

